### ISSUE TITLE
Looking forward to HierVST and Diff-HierVC

### ISSUE THREAD

**Issue by TinaChen95** [sh-lee-prml/sh-lee-prml#1]
Hello, 

I could not find pdf for paper HierVST and Diff-HierVC. Are they publicly available now?

Thanks

**Comment by sh-lee-prml** [comment]
Hello!

The Interspeech2023 proceedings will be available in Aug. 

Before that, please visit our demo page!

[[HierVST demo page]](https://hiervst.github.io/)

Thanks

**Comment by sh-lee-prml** [comment]
Hi 

https://arxiv.org/abs/2307.16171

HierVST was uploaded at Arxiv!

Diff-HierVC will be also uploaded in next week.

Thanks
